#kitty.conf

include ./theme.conf


#font_family      Terminess Nerd Font
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      Operator Mono Bold Italic
bold_italic_font auto
font_size        11

mouse_hide_wait 3.0

enable_audio_bell no

window_padding_width 5
hide_window_decorations titlebar-only

background_opacity 0.95
dynamic_background_opacity yes

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9





#  λ opt

# mac - font_size 12 - font_family Terminess Nerd Font
# monitor - font_size 9 - font_family Terminess Nerd Font
# mac - font_size 11 - font_family JetBrainsMono Nerd Font Mono
# monitor - font_size 8 - font_family JetBrainsMono Nerd Font Mono
